### PR TITLE
Add new Google Weater Material You icons

### PR DESCRIPTION
**Pull request by fishaffair**
I think they are missed here, new redesigned weather icons from Google are awesome 😊
Credits for extraction: 

https://gitlab.com/bignutty/google-weather-icons
https://github.com/bignutty/google-weather-icons

### CODE REVIEW

**Comment by fishaffair** [comment]
@neobuddy89 Please review, thnx

**Comment by fishaffair** [comment]
@neobuddy89 Please review, thanks!

**Comment by gwolf2u** [comment]
think we need a more optimized format
adding lots of pngs will result in bigger partition size on devices with limited space for not a big benefit

**Comment by fishaffair** [comment]
> think we need a more optimized format adding lots of pngs will result in bigger partition size on devices with limited space for not a big benefit

My addition is only about 2MB - not so big. Maybe I can place .svgs  if `/res/drawable`  if this a more apropriate way.

**Comment by gwolf2u** [comment]
added new icons
https://github.com/crdroidandroid/android_packages_services_OmniJaws/commit/63d6f9760940c8f3bee4c2bd143f317c6eb2037d
https://github.com/crdroidandroid/android_packages_services_OmniJaws/commit/0924bd2e39d503fb5dfdffc2736afe223e7eee7d

**Pull request closed without merging**
